# Generated by Django 4.2.30 on 2026-05-25 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Corporate Travel Export')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('raw_metadata', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct'), (2, 'Scope 2 — Indirect Electricity'), (3, 'Scope 3 — Value Chain')])),
                ('category', models.CharField(choices=[('FUEL_STATIONARY', 'Stationary Combustion'), ('FUEL_MOBILE', 'Mobile Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('TRAVEL_AIR', 'Business Travel — Air'), ('TRAVEL_HOTEL', 'Business Travel — Hotel'), ('TRAVEL_GROUND', 'Business Travel — Ground'), ('PROCUREMENT', 'Purchased Goods & Services')], max_length=50)),
                ('activity_date', models.DateField()),
                ('activity_description', models.TextField(blank=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_source_row', models.JSONField(default=dict)),
                ('quantity_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_used', models.CharField(blank=True, max_length=255)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('source_location', models.CharField(blank=True, max_length=500)),
                ('source_entity', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged — Needs Attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INGESTED', 'Record Ingested'), ('FLAGGED', 'Auto-Flagged'), ('APPROVED', 'Approved by Analyst'), ('REJECTED', 'Rejected'), ('EDITED', 'Field Edited'), ('LOCKED', 'Locked for Audit'), ('NOTE_ADDED', 'Note Added')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_e_tenant__281016_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='ingestion_e_tenant__87a790_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='ingestion_e_batch_i_e7d0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='ingestion_e_activit_d0ada0_idx'),
        ),
    ]
