"""
SAP Flat-File Parser (IDoc-style tab-delimited export).

WHY FLAT FILE: SAP IDoc flat files are the most common export format
in environments that don't have active API integrations. OData is
cleaner but requires SAP Netweaver Gateway configuration that most
clients haven't done. BAPIs require ABAP expertise on client side.
Flat file can be generated by any SAP user with SE16 or MB51 access.

Expected columns (subset of MB51 movement report):
  BUDAT  = Posting Date (YYYYMMDD or DD.MM.YYYY)
  WERKS  = Plant Code
  MATNR  = Material Number
  MAKTX  = Material Description
  MENGE  = Quantity
  MEINS  = Unit of Measure (SAP UoM code, e.g. L, KG, M3, GJ)
  DMBTR  = Amount in local currency
  BWART  = Movement Type (201=consumption, 261=goods issue to order)
"""

import pandas as pd
import io
from decimal import Decimal
from datetime import datetime

# SAP UoM codes → normalized unit strings
SAP_UOM_MAP = {
    'L':   'liters',
    'LTR': 'liters',
    'KG':  'kg',
    'G':   'grams',
    'M3':  'm3',
    'GJ':  'GJ',
    'KWH': 'kWh',
    'MJ':  'MJ',
    'T':   'tonnes',
    'ST':  'pieces',  # Stück — will be flagged as non-energy
}

# Movement types we care about (fuel/energy consumption)
RELEVANT_MOVEMENT_TYPES = {'201', '261', '551', '901'}

# Fuel material keyword hints (from MAKTX description)
FUEL_KEYWORDS = [
    'diesel', 'petrol', 'benzin', 'heizöl', 'fuel oil',
    'natural gas', 'erdgas', 'lpg', 'propane', 'kerosene',
]


def parse_sap_flat_file(file_content: bytes) -> dict:
    """
    Parse SAP flat file export. Returns dict with:
      - records: list of normalized dicts ready for EmissionRecord creation
      - errors: list of row-level parse failures
      - metadata: detected headers, encoding, row counts
    """
    records = []
    errors = []

    # Detect encoding — SAP often exports in Latin-1 from German systems
    for encoding in ['utf-8', 'latin-1', 'cp1252']:
        try:
            text = file_content.decode(encoding)
            break
        except UnicodeDecodeError:
            continue
    else:
        return {'records': [], 'errors': ['Could not decode file'], 'metadata': {}}

    # Try tab-delimited first, then semicolon (SAP varies by locale)
    for sep in ['\t', ';', ',']:
        try:
            df = pd.read_csv(io.StringIO(text), sep=sep, dtype=str)
            if len(df.columns) >= 5:
                break
        except Exception:
            continue

    df.columns = [c.strip().upper() for c in df.columns]
    metadata = {'original_columns': list(df.columns), 'row_count': len(df), 'encoding': encoding}

    # Column name normalization — handle German headers
    col_map = {
        'BUDAT': 'BUDAT', 'BUCHUNGSDATUM': 'BUDAT', 'POSTING DATE': 'BUDAT',
        'WERKS': 'WERKS', 'PLANT': 'WERKS', 'WERK': 'WERKS',
        'MATNR': 'MATNR', 'MATERIAL': 'MATNR', 'MATERIALNUMMER': 'MATNR',
        'MAKTX': 'MAKTX', 'MATERIAL DESCRIPTION': 'MAKTX', 'BEZEICHNUNG': 'MAKTX',
        'MENGE': 'MENGE', 'QUANTITY': 'MENGE', 'MENGE IN ERFME': 'MENGE',
        'MEINS': 'MEINS', 'UOM': 'MEINS', 'UNIT': 'MEINS', 'EINHEIT': 'MEINS',
        'BWART': 'BWART', 'MOVEMENT TYPE': 'BWART', 'BEWEGUNGSART': 'BWART',
    }
    df.rename(columns={c: col_map.get(c, c) for c in df.columns}, inplace=True)

    required = ['BUDAT', 'WERKS', 'MENGE', 'MEINS']
    missing = [r for r in required if r not in df.columns]
    if missing:
        return {
            'records': [],
            'errors': [f'Missing required columns: {missing}. Found: {list(df.columns)}'],
            'metadata': metadata,
        }

    for idx, row in df.iterrows():
        try:
            # Filter movement types
            bwart = str(row.get('BWART', '')).strip()
            if bwart and bwart not in RELEVANT_MOVEMENT_TYPES:
                continue

            # Parse date — SAP uses YYYYMMDD or DD.MM.YYYY
            raw_date = str(row['BUDAT']).strip()
            activity_date = _parse_sap_date(raw_date)
            if not activity_date:
                errors.append({'row': idx, 'error': f'Unparseable date: {raw_date}', 'raw': dict(row)})
                continue

            # Quantity
            raw_qty = str(row['MENGE']).replace(',', '.').strip()
            quantity = Decimal(raw_qty)
            if quantity <= 0:
                continue  # Skip zero/negative consumption rows

            # Unit normalization
            raw_unit = str(row.get('MEINS', '')).strip().upper()
            normalized_unit = SAP_UOM_MAP.get(raw_unit)
            if not normalized_unit:
                errors.append({'row': idx, 'error': f'Unknown UoM: {raw_unit}', 'raw': dict(row)})
                normalized_unit = raw_unit  # keep going, flag it

            # Material description — detect fuel type
            description = str(row.get('MAKTX', row.get('MATNR', ''))).strip()
            is_fuel = any(kw in description.lower() for kw in FUEL_KEYWORDS)

            record = {
                'activity_date': activity_date,
                'activity_description': description,
                'raw_quantity': quantity,
                'raw_unit': normalized_unit,
                'raw_source_row': dict(row),
                'source_location': str(row.get('WERKS', '')).strip(),
                'source_entity': str(row.get('MATNR', '')).strip(),
                'scope': 1,
                'category': 'FUEL_STATIONARY' if is_fuel else 'PROCUREMENT',
                'flag_reason': '' if is_fuel else 'Non-fuel material — verify category',
                'status': 'PENDING' if is_fuel else 'FLAGGED',
            }
            records.append(record)

        except Exception as e:
            errors.append({'row': idx, 'error': str(e), 'raw': dict(row)})

    return {'records': records, 'errors': errors, 'metadata': metadata}


def _parse_sap_date(raw: str) -> str | None:
    for fmt in ('%Y%m%d', '%d.%m.%Y', '%d/%m/%Y', '%Y-%m-%d', '%m/%d/%Y'):
        try:
            return datetime.strptime(raw, fmt).strftime('%Y-%m-%d')
        except ValueError:
            continue
    return None
